-- Script runs daily but produces new records only Mondays


WITH FIRST_PERIOD AS (
WITH CHECKUP AS
(
	SELECT  SCHEDULE_CREATE_DATE
	       ,SCHEDULE_ID
	       ,CUSTOMER_ITEM
	       ,COST
	       ,SUM(QTY) OVER (PARTITION BY SCHEDULE_CREATE_DATE,SCHEDULE_ID,CUSTOMER_ITEM ORDER BY SCHEDULE_CREATE_DATE DESC,SCHEDULE_ID DESC) AS QTY
	       ,PART_KEY
	       ,CUSTOMER_KEY
	       ,SITE_KEY
	       ,ROW_NUMBER () OVER(PARTITION BY CUSTOMER_ITEM ORDER BY SCHEDULE_CREATE_DATE DESC,SCHEDULE_ID DESC) AS RANKS
	FROM CUSTOMER_SCHEDULE
	WHERE
    SCHEDULED_DATE BETWEEN DATE_TRUNC('WEEK', CURRENT_DATE())+1 AND DATEADD('WEEK', 4, DATE_TRUNC('WEEK', CURRENT_DATE())+1)-1
	AND SCHEDULE_CREATE_DATE <= DATE_TRUNC('WEEK', CURRENT_DATE())+1 --CURRENT_MONDAY
	AND SCHEDULE_CREATE_DATE >= DATEADD('MONTH', -1, CURRENT_DATE()) 
	AND SCHEDULE_SCHEDULE_TYPE = 1
)
SELECT 
  SCHEDULE_CREATE_DATE
	,SCHEDULE_ID
	,CUSTOMER_ITEM
	,COST
	,QTY
	,PART_KEY
	,CUSTOMER_KEY
	,SITE_KEY
  ,SPLIT_PART(PART_KEY,'~',-1) AS PART
	,RANKS
FROM 
    CHECKUP
WHERE 
    RANKS = '1'
),
SECOND_PERIOD AS (
WITH CHECKUP2 AS
(
	SELECT  SCHEDULE_CREATE_DATE
	       ,SCHEDULE_ID
	       ,CUSTOMER_ITEM
	       ,COST
	       ,SUM(QTY) OVER (PARTITION BY SCHEDULE_CREATE_DATE,SCHEDULE_ID,CUSTOMER_ITEM ORDER BY SCHEDULE_CREATE_DATE DESC,SCHEDULE_ID DESC) AS QTY
	       ,PART_KEY
	       ,CUSTOMER_KEY
	       ,SITE_KEY
	       ,ROW_NUMBER () OVER(PARTITION BY CUSTOMER_ITEM ORDER BY SCHEDULE_CREATE_DATE DESC,SCHEDULE_ID DESC) AS RANKS
	FROM CUSTOMER_SCHEDULE
	WHERE
    SCHEDULED_DATE BETWEEN DATEADD('DAY',+7,DATE_TRUNC('WEEK', CURRENT_DATE())+1) AND DATEADD('WEEK',4,DATEADD('DAY',+7,DATE_TRUNC('WEEK', CURRENT_DATE())))
	AND SCHEDULE_CREATE_DATE <= DATE_TRUNC('WEEK', CURRENT_DATE())+1 --CURRENT_MONDAY
	AND SCHEDULE_CREATE_DATE >= DATEADD('MONTH', -1, CURRENT_DATE()) 
	AND SCHEDULE_SCHEDULE_TYPE = 1
    
)
SELECT
   SCHEDULE_CREATE_DATE
	,SCHEDULE_ID
	,CUSTOMER_ITEM
	,COST
	,QTY
	,PART_KEY
	,CUSTOMER_KEY
	,SITE_KEY
    ,SPLIT_PART(PART_KEY,'~',-1) AS PART
	,RANKS
FROM 
   CHECKUP2
WHERE 
    RANKS = 1
)
SELECT 
    CURRENT_DATE() AS SNAPSHOT_DATE
    ,A.SCHEDULE_CREATE_DATE
	,A.SCHEDULE_ID
	,A.CUSTOMER_ITEM
	,A.COST
    ,A.QTY                                           AS QTY_FIRST_PERIOD
    ,B.QTY                                           AS QTY_SECOND_PERIOD
    ,QTY_FIRST_PERIOD * A.COST  AS TOTAL_COST_FIRST_PERIOD
    ,QTY_SECOND_PERIOD * A.COST AS TOTAL_COST_SECOND_PERIOD
	,A.PART_KEY
	,A.CUSTOMER_KEY
	,A.SITE_KEY
FROM 
    FIRST_PERIOD A
JOIN 
    SECOND_PERIOD B ON
        A.CUSTOMER_ITEM = B.CUSTOMER_ITEM 
        AND A.PART = B.PART
WHERE 
    A.RANKS = 1
    AND B.RANKS = 1
    AND CURRENT_DATE() = DATE_TRUNC('WEEK', CURRENT_DATE())+1
