WITH RECURSIVE NUM_SERIES AS (
  SELECT 0 AS NUM
  UNION ALL
  SELECT NUM + 1
  FROM NUM_SERIES
  WHERE NUM < 64
),
DATE_SERIES AS (
  SELECT 
  TO_DATE('2020-01-01','YYYY-MM-DD') AS CURRENT_DAY_DT
  UNION ALL
  SELECT CURRENT_DAY_DT + 1
  FROM DATE_SERIES
  WHERE CURRENT_DAY_DT + 1 <= DATE('2035-12-31')
)
SELECT 
  DS.CURRENT_DAY_DT,
  DS.CURRENT_DAY_DT + NS.NUM AS WORKING_DAY_DT,
  NS.NUM AS WORKING_DAY_OFFSET,
  TO_CHAR(DS.CURRENT_DAY_DT, 'YYYYMMDD')::INTEGER AS CURRENT_DAY_KEY,
  TO_CHAR(WORKING_DAY_DT, 'YYYYMMDD')::INTEGER AS WORKING_DAY_KEY
FROM DATE_SERIES DS
CROSS JOIN NUM_SERIES NS
ORDER BY DS.CURRENT_DAY_DT, NS.NUM,WORKING_DAY_OFFSET;


## How to use it properly?

SELECT 
    SHIP_DATE
    ,
    ,WD.WORKING_DAY_DT AS ETA
FROM <MY_TABLE>
    LEFT JOIN WORKING_DAYS_TABLE WD ON 
        SHIP_DATE = WD.CURRENT_DAY_DT AND TRANSPORT_DAYS = WD.WORKING_DAY_OFFSET;

## IF the SHIP_DATE would be on Friday and TRANSPORT_DAYS would be 3 days
## it will take the weekend into consideration therefore the DELIVERY_DATE would be TUE if the Goods are SHIPPED on FRIDAY.
